### ISSUE TITLE
[p2p Code Review] Suggestions for improvement

### ISSUE THREAD

**Issue by gvgesanto2** [GiuseppeTG/Book-App#2]
## Hi @GiuseppeTG  👋,

Your code is top-notch, congrats!

## To Highlight 💯 
✔️ Very good solution to the problem 
✔️ Very well organized code
✔️ The way you isolated your classes by concern, keeping your app business logic separated from the presentation logic (DOM manipulation tasks), is very good! Congrats!

## Suggestions
- This is the way you are removing a book from your books array right now: 
  ```js
  static removeBook(title) {
    const books = Store.getBooks();
    books.forEach((book, index) => {
      if (book.title === title) {
        books.splice(index, 1);
      }
    });
    localStorage.setItem('books', JSON.stringify(books));
  }
  ```
  This is not working properly right now. Depending on which book the user deletes from your list, this will create 
  inconsistencies between your data structure used by your ``Store class`` and the list of books displayed on the screen (you will 
  remove the correct book from the screen, but the wrong one from the local storage). This problem happens because you are 
  relying on the property ``title`` to make the remotion, which is not a unique property between all the books (more than one 
  book can have the same title). 
  So, to solve this problem the key concept is: **for deleting a specific book from your data structure you need to rely on a 
  property that is always going to be unique for all the books.** 
  So, one of the options could be to create an id property in your ``Book`` class that's going to be initialized with a unique value 
  every time you create a book. As an example, you could do this:
  ```js
    // Using this solution don't forget that the class Store declaration needs to be defined before the class Book
    // (so you can use the method "Store.getBooks()" inside your Book's constructor)
    const genNewIdForElem = (elemsArray) => {
      if (elemsArray.length > 0) {
        return elemsArray[elemsArray.length - 1].id + 1;
       }
      return 1;
    };
   class Book {
     constructor(title, author) {
       this.title = title;
       this.author = author;
       this.id = genNewIdForElem(Store.getBooks());
     }
    }
  ```

**Comment by GiuseppeTG** [comment]
Thank you so much for pointing out that issue!
I'll be working on that 💯
